/*
 * Created by IntelliJ IDEA.
 * Language: Java
 * Property of Umesh Gunasekara
 * @Author: SLMORA
 * @DateTime: 6/11/2026 12:00 AM
 *
 * This source file was generated by the Gradle 'init' task
 */
package com.slmora.patreonpostautodownloader.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import com.slmora.patreonpostautodownloader.sandbox.app.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
