APP.URL_INPUT_PATH=${URL_INPUT_PATH}

APP.EXCEL_OUTPUT_DIR_PATH=${EXCEL_OUTPUT_DIR_PATH}
APP.IMAGE_OUTPUT_DIR_PATH=${IMAGE_OUTPUT_DIR_PATH}
APP.DOCX_OUTPUT_DIR_PATH=${DOCX_OUTPUT_DIR_PATH}
APP.FAILD_OUTPUT_DIR_PATH=${FAILD_OUTPUT_DIR_PATH}

#APP.EXCEL_POST_SHEET_NAME=Posts
#APP.EXCEL_POST_FILE_NAME=patreon_posts_output_temp.xlsx
#
#APP.DOCX_POST_FILE_NAME_PATTERN=patreon_posts_output(.*)\.xlsx
#APP.DOCX_POST_FILE_NAME=patreon_posts_report_temp.docx

APP.EXCEL_QUEUE_CAPACITY=${EXCEL_QUEUE_CAPACITY}
APP.DOCX_QUEUE_CAPACITY=${DOCX_QUEUE_CAPACITY}
APP.RETRY_QUEUE_CAPACITY=${RETRY_QUEUE_CAPACITY}
APP.FAILED_QUEUE_CAPACITY=${FAILED_QUEUE_CAPACITY}

APP.PROCESS_IMAGE_DOWNLOAD_THREADS=${PROCESS_IMAGE_DOWNLOAD_THREADS}
APP.PROCESS_DOCX_THREADS=${PROCESS_DOCX_THREADS}
APP.PROCESS_EXCEL_THREADS=${PROCESS_EXCEL_THREADS}

APP.MAX_RETRY=${MAX_RETRY}

APP.PATREON_ACCESS_COOKIE=${PATREON_ACCESS_COOKIE}