APP.URL_INPUT_PATH=E:\\MORA\\MyBusiness\\Investment\\JU\\AUTO02\\input_url.txt

APP.EXCEL_OUTPUT_DIR_PATH=E:\\MORA\\MyBusiness\\Investment\\JU\\AUTO02\\Post\\Excel
APP.IMAGE_OUTPUT_DIR_PATH=E:\\MORA\\MyBusiness\\Investment\\JU\\AUTO02\\Image
APP.DOCX_OUTPUT_DIR_PATH=E:\\MORA\\MyBusiness\\Investment\\JU\\AUTO02\\Post\\Docx
APP.FAILD_OUTPUT_DIR_PATH=E:\\MORA\\MyBusiness\\Investment\\JU\\AUTO02\\Faild

#APP.EXCEL_POST_SHEET_NAME=Posts
#APP.EXCEL_POST_FILE_NAME=patreon_posts_output_temp.xlsx
#
#APP.DOCX_POST_FILE_NAME_PATTERN=patreon_posts_output(.*)\.xlsx
#APP.DOCX_POST_FILE_NAME=patreon_posts_report_temp.docx

APP.EXCEL_QUEUE_CAPACITY=500
APP.DOCX_QUEUE_CAPACITY=500
APP.RETRY_QUEUE_CAPACITY=1000
APP.FAILED_QUEUE_CAPACITY=5000

APP.PROCESS_IMAGE_DOWNLOAD_THREADS=10
APP.PROCESS_DOCX_THREADS=3
APP.PROCESS_EXCEL_THREADS=3

APP.MAX_RETRY=3

APP.PATREON_ACCESS_COOKIE=REMOVED_SECRET